# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# Ruby version
ruby '2.7.1'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]

# Middleman Gems
gem 'middleman', '~> 4.3.7'
gem 'middleman-livereload'

# Other Gems
gem 'middleman-minify-html'
gem 'middleman-ogp'
gem 'middleman-search_engine_sitemap'

if RUBY_PLATFORM =~ /linux/
  gem 'mini_racer' # faster JS compiles
  gem 'oj' # faster JS compiles
end
